# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WallDit Qt.ui'
#
# Created: Sun Dec  6 00:12:03 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(341, 220)
        font = QtGui.QFont()
        font.setUnderline(False)
        MainWindow.setFont(font)
        self.horizontalLayout = QtGui.QHBoxLayout(MainWindow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.subreddit_label = QtGui.QLabel(MainWindow)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.subreddit_label.setFont(font)
        self.subreddit_label.setObjectName("subreddit_label")
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.subreddit_label)
        self.subreddit_line = QtGui.QLineEdit(MainWindow)
        self.subreddit_line.setMaximumSize(QtCore.QSize(149, 16777215))
        self.subreddit_line.setObjectName("subreddit_line")
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.subreddit_line)
        self.amount_label = QtGui.QLabel(MainWindow)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.amount_label.setFont(font)
        self.amount_label.setObjectName("amount_label")
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.LabelRole, self.amount_label)
        self.post_amount_spinbox = QtGui.QSpinBox(MainWindow)
        self.post_amount_spinbox.setProperty("value", 15)
        self.post_amount_spinbox.setObjectName("post_amount_spinbox")
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.FieldRole, self.post_amount_spinbox)
        self.post_type_label = QtGui.QLabel(MainWindow)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.post_type_label.setFont(font)
        self.post_type_label.setObjectName("post_type_label")
        self.formLayout_6.setWidget(7, QtGui.QFormLayout.LabelRole, self.post_type_label)
        self.post_type_combo_box = QtGui.QComboBox(MainWindow)
        self.post_type_combo_box.setObjectName("post_type_combo_box")
        self.post_type_combo_box.addItem("")
        self.post_type_combo_box.addItem("")
        self.post_type_combo_box.addItem("")
        self.post_type_combo_box.addItem("")
        self.post_type_combo_box.addItem("")
        self.post_type_combo_box.addItem("")
        self.post_type_combo_box.addItem("")
        self.formLayout_6.setWidget(7, QtGui.QFormLayout.FieldRole, self.post_type_combo_box)
        self.boot_checkbox = QtGui.QCheckBox(MainWindow)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setBold(True)
        self.boot_checkbox.setFont(font)
        self.boot_checkbox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.boot_checkbox.setObjectName("boot_checkbox")
        self.formLayout_6.setWidget(8, QtGui.QFormLayout.FieldRole, self.boot_checkbox)
        self.nsfw_checkbox = QtGui.QCheckBox(MainWindow)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.nsfw_checkbox.setFont(font)
        self.nsfw_checkbox.setObjectName("nsfw_checkbox")
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.nsfw_checkbox)
        self.verticalLayout_3.addLayout(self.formLayout_6)
        self.status_label = QtGui.QLabel(MainWindow)
        self.status_label.setFrameShape(QtGui.QFrame.StyledPanel)
        self.status_label.setFrameShadow(QtGui.QFrame.Plain)
        self.status_label.setLineWidth(1)
        self.status_label.setScaledContents(False)
        self.status_label.setWordWrap(True)
        self.status_label.setObjectName("status_label")
        self.verticalLayout_3.addWidget(self.status_label)
        self.progressBar = QtGui.QProgressBar(MainWindow)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.start_btn = QtGui.QPushButton(MainWindow)
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout_3.addWidget(self.start_btn)
        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "WallDit by Disco Dolan", None, QtGui.QApplication.UnicodeUTF8))
        self.subreddit_label.setToolTip(QtGui.QApplication.translate("MainWindow", "You can use multireddits (add a + between each subreddit)", None, QtGui.QApplication.UnicodeUTF8))
        self.subreddit_label.setText(QtGui.QApplication.translate("MainWindow", "Subreddit(s):", None, QtGui.QApplication.UnicodeUTF8))
        self.subreddit_line.setToolTip(QtGui.QApplication.translate("MainWindow", "You can use multireddits (add a + between each subreddit)", None, QtGui.QApplication.UnicodeUTF8))
        self.subreddit_line.setText(QtGui.QApplication.translate("MainWindow", "Wallpaper+Wallpapers", None, QtGui.QApplication.UnicodeUTF8))
        self.amount_label.setToolTip(QtGui.QApplication.translate("MainWindow", "Dictates how many posts it looks for before stopping", None, QtGui.QApplication.UnicodeUTF8))
        self.amount_label.setText(QtGui.QApplication.translate("MainWindow", "Amount of posts to look for:", None, QtGui.QApplication.UnicodeUTF8))
        self.post_amount_spinbox.setToolTip(QtGui.QApplication.translate("MainWindow", "Dictates how many posts it looks for before stopping", None, QtGui.QApplication.UnicodeUTF8))
        self.post_type_label.setText(QtGui.QApplication.translate("MainWindow", "Which posts to fetch:", None, QtGui.QApplication.UnicodeUTF8))
        self.post_type_combo_box.setItemText(0, QtGui.QApplication.translate("MainWindow", "Hot", None, QtGui.QApplication.UnicodeUTF8))
        self.post_type_combo_box.setItemText(1, QtGui.QApplication.translate("MainWindow", "Top this Hour", None, QtGui.QApplication.UnicodeUTF8))
        self.post_type_combo_box.setItemText(2, QtGui.QApplication.translate("MainWindow", "Top this Day", None, QtGui.QApplication.UnicodeUTF8))
        self.post_type_combo_box.setItemText(3, QtGui.QApplication.translate("MainWindow", "Top this Week", None, QtGui.QApplication.UnicodeUTF8))
        self.post_type_combo_box.setItemText(4, QtGui.QApplication.translate("MainWindow", "Top this Month", None, QtGui.QApplication.UnicodeUTF8))
        self.post_type_combo_box.setItemText(5, QtGui.QApplication.translate("MainWindow", "Top this Year", None, QtGui.QApplication.UnicodeUTF8))
        self.post_type_combo_box.setItemText(6, QtGui.QApplication.translate("MainWindow", "Top all Time", None, QtGui.QApplication.UnicodeUTF8))
        self.boot_checkbox.setToolTip(QtGui.QApplication.translate("MainWindow", "When toggled, starts on boot", None, QtGui.QApplication.UnicodeUTF8))
        self.boot_checkbox.setText(QtGui.QApplication.translate("MainWindow", "Start on boot", None, QtGui.QApplication.UnicodeUTF8))
        self.nsfw_checkbox.setToolTip(QtGui.QApplication.translate("MainWindow", "Toggle to enable searching for NSFW links", None, QtGui.QApplication.UnicodeUTF8))
        self.nsfw_checkbox.setText(QtGui.QApplication.translate("MainWindow", "NSFW", None, QtGui.QApplication.UnicodeUTF8))
        self.status_label.setText(QtGui.QApplication.translate("MainWindow", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.start_btn.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))

